branches:
  only:
  - fathon-dev

env:
  global:
    - CIBW_BUILD_VERBOSITY=3
#    - CIBW_BUILD="cp35-* cp36-* cp37-* cp38-*"
    - CIBW_BUILD="cp37-*"
    - CIBW_SKIP: "*-manylinux_i686"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}/tests"
    - CIBW_BEFORE_BUILD="pip3 install -r requirements.txt"

matrix:
  include:
    # ===== Linux ======
    - name: "Python 3.7 on Linux"
      language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
        - docker
#    # ======= macOS ========
#    - name: "Python 3.7.3 on macOS 10.14"
#      os: osx
#      osx_image: xcode10.2
#      language: shell

before_install:
  - python3 --version

install:
  - pip3 install --upgrade cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
  - pip install twine
  - twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing wheelhouse/* -u ${TEST_PYPI_USR} -p ${TEST_PYPI_PWD}
