branches:
  only:
  - fathon-dev

#env:
#  global:
#    - CIBW_BUILD="cp35-* cp36-* cp37-* cp38-*"

matrix:
  include:
    # ===== Linux ======
    - name: "Python 3.5 on Linux"
      language: python
      dist: xenial
      python: "3.5"
      services:
        - docker
    # ======= macOS ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4
      language: shell
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.8 on macOS 10.14"
      os: osx
      osx_image: xcode10.2
      language: shell

before_install:
  - python3 --version

install:
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install -r requirements.txt
  - pip3 install .
#  - pip3 install twine
#  - pip3 install cibuildwheel

script:
  - pytest tests
#  - cibuildwheel --output-dir wheelhouse
#  - twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/* -u ${TEST_PYPI_USR} -p ${TEST_PYPI_PWD}
