language: python

branches:
  only:
  - fathon-dev

# ===== Linux ======
dist: xenial
python:
  - 3.7
matrix:
  include:      
    # ======= macOS ========
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest pytest-cov
        - pip3 install codecov
        - pip3 install -r requirements.txt
      install:
        - pip3 install .
      script:
        - pytest tests
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest pytest-cov
  - pip3 install codecov
  - pip3 install -r requirements.txt
install:
  - pip3 install .
script:
  - pytest tests
