language: python

branches:
  only:
  - fathon-dev

matrix:
  include:
    - name: "Python 3.7 on Linux"
      language: python
      dist: xenial
      sudo: required
      python: "3.7"
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install -r requirements.txt
      install:
        - pip3 -v install .
      script:
        - pytest tests
    # ======= macOS ========
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - xcode-select --install
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install -r requirements.txt
        - echo $CFLAGS
      install:
        - CFLAGS="-Xpreprocessor -fopenmp" pip3 -v install .
        - echo $CFLAGS
      script:
        - pytest tests

